### ISSUE TITLE
Wrong answer

### ISSUE THREAD

**Issue by peto2006** [tranleduy2000/ncalc#59] opened 2018-09-07 10:51 UTC
Enter this into equation solver:`30*x/0.0002=30`. It returns result `x = 1.4365636569180902`. When you add more zeros before 2, it also produces bad result. If you remove one zero, it produces good result.

I'm unable to find where the problem is, so at least I'm creating this issue.

**Comment by LenticularAurora** [comment] 2018-09-29 11:18
Why is the result wrong? The answer to the following equation is: 1/5000 which is the same as x = 1.4365636569180902.

**Comment by peto2006** [comment] 2018-10-01 21:10
As you have said, 30x/0.0002 = 30 => x = **2.0 * 10^-4**, or **1/5000** or **0.0002**, not _1.4365636569180902_.

**Comment by LenticularAurora** [comment] 2018-10-03 22:01
Sorry, wrote that in a messed up way and had to edit the writing.. I'll check what the problem is and try to fix the issue because sadly the owner of this application (if I am not mistaken) has stopped fixing issues proposed by users and is taking pull requests at the moment (not sure if he/she plans on going back to developing this calculator or not).

**Comment by axkr** [comment] 2019-07-02 18:22
Fixed with 3.4.3-beta

**Closed** 2019-07-06 19:41 UTC
