### ISSUE TITLE
Bad results

### ISSUE THREAD

**Issue by Manu99it** [tranleduy2000/ncalc#62] opened 2018-12-11 22:15 UTC
I think this calculator has some problems on giving results, maybe has the same bug of commodore 64 (C64 was using only 8byte memory to calculate things, so it couldn't store infinite numbers from 0.1 and 1. See this for reference http://www.mos6502.com/friday-commodore/crazy-numbers-on-the-c64/):
If you submit to the calculator 0.1+0.1+0.1 (either with the plus ide functionality) it gives 0.30000000000000004
But that isn't the only bug: everything related to that give wrong results (e.a. other bugs are 0.1•3 or 0.1•7 or 0.1+0.1+0.1+0.1+0.1+0.1+0.1+0.1)

**Comment by PseudoResonance** [comment] 2018-12-30 02:04
Duplicate of #10 

This is a floating point rounding error.

**Comment by Manu99it** [comment] 2018-12-30 02:16
Yup true, I didn't know. Hopefully this could be fixed in a some way!

**Comment by axkr** [comment] 2019-07-02 18:21
Fixed with 3.4.3-beta

**Closed** 2019-07-06 19:41 UTC
