### ISSUE TITLE
Deploy to F-Droid

### ISSUE THREAD

**Issue by fox8091** [tranleduy2000/ncalc#20] opened 2017-11-07 04:34 UTC
Would you consider releasing your app on F-Droid as well for those who prefer it over Play Store?

**Comment by Madis0** [comment] 2017-11-07 18:20
Duplicate of #6

**Comment by fox8091** [comment] 2017-11-07 18:46
Sorry, I must've missed that. Thanks anyways!

**Closed** 2017-11-07 18:47 UTC
